apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-service
  namespace: test-space
spec:
  selector:
    app: hello-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
